; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter, extra scripting
;   Upload options: custom port, speed and extra flags
;   Library options: dependencies, extra library storages
;
; Please visit documentation for the other options and examples
; http://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = .
default_envs = tu_prod

[env]
; platform = teensy@4.8.0 ; 1.51
platform = teensy@4.14.0 ; 1.55
framework = arduino
board = teensy31
board_build.f_cpu = 120000000
lib_deps = EEPROM
build_flags =
  -DTEENSY_OPT_FASTER
  !echo "-DTU_BUILD_TAG='\"$(resources/tu_build_tag.sh)\"'"

extra_scripts = pre:resources/progname.py

monitor_speed = 115200
monitor_port = /dev/tty.usbmodem75026601

[env:tu_prod]
build_flags =
  ${env.build_flags}

[env:tu_dev]
targets = upload
build_flags =
  ${env.build_flags}
  -DDUSB_SERIAL
  -DTU_SERIAL_WAIT
  -DTU_ADC_DEBUG_SERIAL
upload_protocol = teensy-cli
